document.write('<nav id="nav" class="nav"><ul><li><a href="index.html">Hjem</a></li>');
document.write('<li><a href="Diagrammer.html">Diagrammer &#9662;</a><ul class="dropdown">');
document.write('<li><a href="Klassediagram.html">Klassediagram</a></li>');
document.write('<li><a href="Objektdiagram.html">Objektdiagram</a></li>');
document.write('<li><a href="Pakkediagram.html">Pakkediagram</a></li>');
document.write('<li><a href="UseCase.html">Use Cases</a></li>');
document.write('<li><a href="Aktivitetsdiagram.html">Aktivitetsdiagram</a></li>');
document.write('<li><a href="Kommunikasjonsdiagram.html">Kommunikasjonsdiagram</a></li>');
document.write('<li><a href="Interaksjonsdiagram.html">Interaksjonsdiagram</a></li>');
document.write('<li><a href="Sekvensdiagram.html">Sekvensdiagram</a></li>');
document.write('<li><a href="Tidsdelingsdiagram.html">Tidsdelingsdiagram</a></li>');
document.write('<li><a href="Tilstandsdiagram.html">Tilstandsdiagram</a></li>');
document.write('</ul></li><li><a href="index.html#om">Gruppen</a></li></ul></nav>');